export const data = [
    {
        country: 'France',
        artist: 'Марсель Руссо',
        title: 'Охота Амура',
        material: 'Холст, масло (50х80)',
        price: 14500,
        image: "./images/France/amur.webp",
    },
        {
        country: 'France',
        artist: 'Анри Селин',
        title: 'Дама с собачкой',
        material: 'Акрил, бумага (50х80)',
        price: 16500,
        image: "./images/France/dogmadam.webp",
    },
        {
        country: 'France',
        artist: 'Франсуа Дюпон',
        title: 'Процедура',
        material: 'Цветная литография (40х60)',
        price: 20000,
        image: "./images/France/treatment.webp",
    },
        {
        country: 'France',
        artist: 'Луи Детуш',
        title: 'Роза',
        material: 'Бумага, акрил (50х80)',
        price: 12000,
        image: "./images/France/rose.webp",
    },
        {
        country: 'France',
        artist: 'Франсуа Дюпон',
        title: 'Птичья трапеза',
        material: 'Цветная литография (40х60)',
        price: 22500,
        image: "./images/France/birds.webp",
    },
        {
        country: 'France',
        artist: 'Пьер Моранж',
        title: 'Пейзаж с рыбой',
        material: 'Цветная литография (40х60)',
        price: 20000,
        image: "./images/France/fish.webp",
    },
        {
        country: 'England',
        artist: 'Пол Смит',
        title: 'Дикий зверь',
        material: 'Акварель, бумага (50х80)',
        price: 19500,
        image: "./images/England/moose.webp",
    },
      {
        country: 'England',
        artist: 'Джон Уайт',
        title: 'Скалистый берег',
        material: 'Цветная литография (40х60)',
        price: 17500,
        image: "./images/England/cliffs.webp",
    },
      {
        country: 'England',
        artist: 'Джим Уотсон',
        title: 'Река и горы',
        material: 'Акварель, бумага (50х80)',
        price: 20500,
        image: "./images/England/river.webp",
    },
      {
        country: 'England',
        artist: 'Юджин Зиллион',
        title: 'Белый попугай',
        material: 'Цветная литография (40х60)',
        price: 15500,
        image: "./images/England/parrot.webp",
    },
       {
        country: 'England',
        artist: 'Эрик Гиллман',
        title: 'Ночная рыба',
        material: 'Бумага, акрил (50х80)',
        price: 12500,
        image: "./images/England/nightfish.webp",
    },
       {
        country: 'England',
        artist: 'Альфред Барр',
        title: 'Рыжий кот',
        material: 'Цветная литография (40х60)',
        price: 21000,
        image: "./images/England/cat.webp",
    },
    {
         country: 'Germany',
        artist: 'Курт Вернер',
        title: 'Над городом',
        material: 'Цветная литография (40х60)',
        price: 16000,
        image: "./images/Germany/abovecity.webp",
    },
    {
        country: 'Germany',
        artist: 'Макс Рихтер',
        title: 'Птенцы',
        material: 'Холст, масло (50х80) ',
        price: 14500,
        image: "./images/Germany/nestlings.webp",
    },
    {
        country: 'Germany',
        artist: 'Мартин Майер',
        title: 'Среди листьев',
        material: 'Цветная литография (40х60) ',
        price: 20000,
        image: "./images/Germany/leaf.webp",
    },
    {
        country: 'Germany',
        artist: 'Герман Беккер',
        title: 'Яркая птица',
        material: 'Цветная литография (40х60) ',
        price: 13000,
        image: "./images/Germany/colorfulbird.webp",
    },
    {
        country: 'Germany',
        artist: 'Вульф Бауэр',
        title: 'Дятлы',
        material: 'Бумага, акрил (50х80) ',
        price: 20000,
        image: "./images/Germany/woodpeckers.webp",
    },
    {
        country: 'Germany',
        artist: 'Вальтер Хартманн',
        title: 'Большие воды',
        material: 'Бумага, акрил (50х80) ',
        price: 23000,
        image: "./images/Germany/water.webp",
    },
];